name: pseudo_pins
version: 2.0.0
description: A Chrome extension to manage tab positions.
authors: George Lesica <george@lesica.com>

environment:
  sdk: ^1.21.0

dependencies:
  chrome: ^0.9.2
  dart_sass_transformer: ^0.5.0
  dart_to_js_script_rewriter: ^1.0.0
  react: ^3.0.0
  w_flux: ^2.6.0
  over_react: ^1.4.0
  w_common: ^1.2.0
  uuid: ^0.5.3

dev_dependencies:
  browser: any
  dart_dev: ^1.6.0
  dart_style: any

transformers:
  - chrome
  - dart_sass_transformer
  - dart_to_js_script_rewriter
  - over_react
  - $dart2js:
      minify: true
      csp: true

